name: get_x_study
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  drift: ^2.25.1
  #drift: ^2.14.0
  #aws_dynamodb_api: ^1.0.0
  aws_dynamodb_api: ^2.0.0
  #aws_signature_v4: ^1.0.0
  aws_signature_v4: ^0.6.3

  flutter:
    sdk: flutter
  get: ^4.6.6
  path: ^1.9.1
  #path_provider: ^2.1.5
  path_provider: ^2.0.0
  #sqlite3_flutter_libs: ^0.5.31
  sqlite3_flutter_libs: ^0.5.0
  flutter_blue_plus: ^1.31.8
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  #drift_dev: ^2.25.2
  drift_dev: ^2.14.0

flutter:
  uses-material-design: true

